apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-example-v1
spec:
  selector:
    matchLabels:
      app: spring-boot-example
      version: "v1"
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: spring-boot-example
        version: "v1"
    spec:
      containers:
      - name: spring-boot-example
        image: 'nginx'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-example
  labels:
    name: spring-boot-example
    version: "v1"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: spring-boot-example
    version: "v1"
  type: LoadBalancer
---  
        
